[package]
name = "ytls-client"
version = "0.0.2"
edition = "2021"
description = "yolox sans-io TLS client context"
homepage = "https://github.com/yolotls/yolotls"
keywords = ["io", "uring", "epoll", "async"]
license = "Apache-2.0/MIT"
readme = "README.md"
repository = "https://github.com/yolotls/yolotls"
categories = ["science"]

[dev-dependencies]
hex = "0.4.3"
rstest = "0.26"
hex-literal = "1.1"
ytls-rustcrypto = { version = "0.0.2", path = "../crypto/rustcrypto" }
rand = { version = "=0.10.0-rc.5", default-features = false, features = ["thread_rng"] }
pem-rfc7468 = { version = "1", default-features = false, features = ["alloc"] }
#pkcs8 = { version = "=0.11.0-rc.8", default-featurs = false }
sec1 = { version = "=0.8.0-rc.10", default-features = false }

[features]
default = []
std = []
zeroize = ["dep:zeroize", "ytls-util/zeroize", "ytls-keys/zeroize"]

[dependencies]
ytls-ctx = { version = "0.0.2", path = "../ctx" }
ytls-extensions = { version = "0.0.1", path = "../extensions" }
ytls-keys = { version = "0.0.2", path = "../keys" }
ytls-traits = { version = "0.0.2", path = "../traits" }
ytls-record = { version = "0.0.2", path = "../record" }
ytls-typed = { version = "0.0.1", path = "../typed" }
ytls-util = { version = "0.0.2", path = "../util" }
rand_core = { version = "=0.10.0-rc-2", default-features = false }
ctutils = { version = "0.3", default-features = false }
# temp debug
#hex = "0.4.3"
zeroize = { version = "1.8", default-features = false, optional = true, features = ["derive"] }
#sha2 = { version = "=0.11.0-rc.3", default-features = false }

[package.metadata.docs.rs]
features = []

#[[example]]
#name = "listener"
