version: 2
updates:
  - package-ecosystem: "cargo"
    directory: "/"
    schedule:
      interval: "daily"
      time: "02:00" # UTC
    reviewers:
      - "pinkforest"
    assignees:
      - "pinkforest"
    labels:
      - "domain: deps"
    commit-message:
      prefix: "* RoboYak deps"
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "daily"
    labels:
      - "domain: ci"
    commit-message:
      prefix: "* RoboYak CI"
